[project]
org-name = "ballerina"
version = "0.0.0"

[dependencies]
"org.wso2.transport.http.netty" = {  version = "6.0.294", path = "./lib/org.wso2.transport.http.netty-6.0.294.jar", groupId = "org.wso2.transport.http" }
"netty-common" = {  version = "4.1.34.Final", path = "./lib/netty-common-4.1.34.Final.jar", groupId = "io.netty" }
"netty-buffer" = {  version = "4.1.34.Final", path = "./lib/netty-buffer-4.1.34.Final.jar", groupId = "io.netty" }
"netty-transport" = {  version = "4.1.34.Final", path = "./lib/netty-transport-4.1.34.Final.jar", groupId = "io.netty" }
"netty-resolver" = {  version = "4.1.34.Final", path = "./lib/netty-resolver-4.1.34.Final.jar", groupId = "io.netty" }
"netty-handler" = {  version = "4.1.34.Final", path = "./lib/netty-handler-4.1.34.Final.jar", groupId = "io.netty" }
"netty-codec-http" = {  version = "4.1.34.Final", path = "./lib/netty-codec-http-4.1.34.Final.jar", groupId = "io.netty" }
"netty-codec" = {  version = "4.1.34.Final", path = "./lib/netty-codec-4.1.34.Final.jar", groupId = "io.netty" }
"netty-handler-proxy" = {  version = "4.1.34.Final", path = "./lib/io.netty-4.1.34.Final.jar", groupId = "io.netty" }
"netty-codec-http2" = {  version = "4.1.34.Final", path = "./lib/netty-codec-http2-4.1.34.Final.jar", groupId = "io.netty" }
"commons-pool" = {  version = "1.5.6.wso2v1", path = "./lib/commons-pool-1.5.6.wso2v1.jar", groupId = "commons-pool.wso2" }
"snakeyaml" = {  version = "1.16.0.wso2v1", path = "./lib/snakeyaml-1.16.0.wso2v1.jar", groupId = "org.wso2.orbit.org.yaml" }
"bcprov-jdk15on" = {  version = "1.61", path = "./lib/bcprov-jdk15on-1.61.jar", groupId = "org.bouncycastle" }
"bcpkix-jdk15on" = {  version = "1.61", path = "./lib/bcpkix-jdk15on-1.61.jar", groupId = "org.bouncycastle" }
"netty-tcnative-boringssl-static" = {  version = "2.0.22.Final", path = "./lib/netty-tcnative-boringssl-static-2.0.22.Final.jar", groupId = "io.netty" }
"commons-lang3" = {  version = "3.5", path = "./lib/commons-lang3-3.5.jar", groupId = "org.apache.commons" }
"mimepull" = {  version = "1.9.7", path = "./lib/mimepull-1.9.7.jar", groupId = "org.jvnet.mimepull" }
"slf4j-api" = {  version = "1.7.22", path = "./lib/slf4j-api-1.7.22.jar", groupId = "org.slf4j" }
"org.wso2.carbon.messaging" = {  version = "2.3.7", path = "./lib/org.wso2.carbon.messaging-2.2.3.jar", groupId = "org.wso2.carbon.messaging" }
"org.wso2.carbon.core" = {  version = "5.1.0", path = "./lib/org.wso2.carbon.core-5.1.0.jar", groupId = "org.wso2.carbon" }
"org.wso2.carbon.secvault" = {  version = "1.0.0", path = "./lib/org.wso2.securevault-1.0.0-wso2v2.jar", groupId = "org.wso2.carbon.secvault" }