[project]
org-name = "ballerina"
version = "0.5.0"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "runtime"
    version = "0.5.0"
    path = "<PATH>/ballerina-runtime-api-2.0.0-Preview6-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["runtime-api"]
