[project]
org-name = "ballerina"
version = "0.0.0"

[dependencies]
"quartz" = {  version = "2.3.1", path = "./lib/quartz-2.3.1.jar", groupId = "org.quartz-scheduler" }
"slf4j-api" = {  version = "1.7.26", path = "./lib/slf4j-api-1.7.26.jar", groupId = "org.slf4j" }
"HikariCP" = {  version = "1.7.26", path = "./lib/HikariCP-3.3.1.jar", groupId = "com.zaxxer" }
