name: Daily build

on:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    timeout-minutes: 75

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: Initialize sub-modules
      run: git submodule update --init

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: |
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        ./gradlew build --scan --max-workers=2

    - name: Upload jballerina-tools.zip
        uses: actions/upload-artifact@v2
        with:
          name: jballerina-tools
          path: ${{ steps.getdist.outputs.file }}

      - name: Get vscode vsix file location
        id: getvscode
        run: echo "::set-output name=file::$(ls tool-plugins/vscode/*.vsix)"

      - name: Upload vscode.vsix
        uses: actions/upload-artifact@v2
        with:
          name: vscode-vsix
          path: ${{ steps.getvscode.outputs.file }}
