name: Publish Ballerina Snapshot

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '8.x'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Build and Publish
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.BAL_BOT_PAT }}
        run: |
          ./gradlew build -x createJavadoc -x test -x check --max-workers=2 --no-daemon
          ./gradlew publish
