name: Publish Ballerina Snapshot

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
          with:
            java-version: 1.8

      - name: Build and Publish
        run: |
          ./gradlew build -x createJavadoc -x test --max-workers=2 --no-daemon
          ./gradlew publish
